name: CI/CD for Static Site with GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  stage-1-checkout:
    name: 1️⃣ Checkout Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

  stage-2-validate-html:
    name: 2️⃣ Validate HTML Syntax
    runs-on: ubuntu-latest
    needs: stage-1-checkout
    steps:
      - uses: actions/checkout@v3

      - name: Install HTML tidy tool
        run: sudo apt-get install -y tidy

      - name: Run tidy to validate HTML
        run: |
          find ./docs -name '*.html' -exec tidy -qe {} \;

  stage-3-check-links:
    name: 3️⃣ Check for Broken Links
    runs-on: ubuntu-latest
    needs: stage-2-validate-html
    steps:
      - uses: actions/checkout@v3

      - name: Install linkchecker
        run: sudo apt-get install -y linkchecker

      - name: Check links in site
        run: linkchecker ./docs/index.html || true

  stage-4-build-preview:
    name: 4️⃣ Build Preview (Optional)
    runs-on: ubuntu-latest
    needs: stage-3-check-links
    steps:
      - uses: actions/checkout@v3

      - name: Archive site preview
        run: zip -r site-preview.zip ./docs

      - name: Upload preview artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-preview
          path: site-preview.zip

  stage-5-deploy:
    name: 5️⃣ Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: stage-4-build-preview
    steps:
      - uses: actions/checkout@v3

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
